import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs) {
	return twMerge(clsx(inputs));
}

export const sampleBooks = [
		{
		  id: '1',
		  title: 'The Great Gatsby',
		  author: 'F. Scott Fitzgerald',
		  genre: 'Fiction',
		  publishedYear: 1925,
		  status: 'Available',
		  description: 'A classic American novel set in the Jazz Age.',
		  isbn: '978-0-7432-7356-5',
		  pages: 180,
		  language: 'English',
		  publisher: 'Scribner',
		},
		{
		  id: '2',
		  title: 'To Kill a Mockingbird',
		  author: 'Harper Lee',
		  genre: 'Fiction',
		  publishedYear: 1960,
		  status: 'Issued',
		  description: 'A gripping tale of racial injustice and childhood innocence.',
		  isbn: '978-0-06-112008-4',
		  pages: 324,
		  language: 'English',
		  publisher: 'J.B. Lippincott & Co.',
		},
		{
		  id: '3',
		  title: '1984',
		  author: 'George Orwell',
		  genre: 'Dystopian',
		  publishedYear: 1949,
		  status: 'Available',
		  description: 'A dystopian social science fiction novel.',
		  isbn: '978-0-452-28423-4',
		  pages: 328,
		  language: 'English',
		  publisher: 'Secker & Warburg',
		},
		{
		  id: '4',
		  title: 'Pride and Prejudice',
		  author: 'Jane Austen',
		  genre: 'Romance',
		  publishedYear: 1813,
		  status: 'Available',
		  description: 'A romantic novel of manners.',
		  isbn: '978-0-14-143951-8',
		  pages: 432,
		  language: 'English',
		  publisher: 'T. Egerton',
		},
		{
		  id: '5',
		  title: 'The Catcher in the Rye',
		  author: 'J.D. Salinger',
		  genre: 'Fiction',
		  publishedYear: 1951,
		  status: 'Issued',
		  description: 'A controversial novel about teenage rebellion.',
		  isbn: '978-0-316-76948-0',
		  pages: 277,
		  language: 'English',
		  publisher: 'Little, Brown and Company',
		},
		{
		  id: '6',
		  title: '1984',
		  author: 'George Orwell1',
		  genre: 'Dystopian',
		  publishedYear: 1949,
		  status: 'Available',
		  description: 'A dystopian social science fiction novel.',
		  isbn: '978-0-452-28423-4',
		  pages: 328,
		  language: 'English',
		  publisher: 'Secker & Warburg',
		},
		{
		  id: '7',
		  title: 'Pride and Prejudice1',
		  author: 'Jane Austen1',
		  genre: 'Romance',
		  publishedYear: 1813,
		  status: 'Available',
		  description: 'A romantic novel of manners.',
		  isbn: '978-0-14-143951-8',
		  pages: 432,
		  language: 'English',
		  publisher: 'T. Egerton',
		},
		{
		  id: '8',
		  title: 'The Catch in the Ryer1',
		  author: 'J.D.T. Salinger1',
		  genre: 'Fiction',
		  publishedYear: 1955,
		  status: 'Issued',
		  description: 'A controversial novel about teenage rebellion.',
		  isbn: '978-0-316-76948-0',
		  pages: 277,
		  language: 'English',
		  publisher: 'Little, Brown and Company',
		},
		{
		  id: '9',
		  title: 'The Great Gatsby1',
		  author: 'F. Scott Fitzgerald1',
		  genre: 'Fiction',
		  publishedYear: 1925,
		  status: 'Available',
		  description: 'A classic American novel set in the Jazz Age.',
		  isbn: '978-0-7432-7356-5',
		  pages: 180,
		  language: 'English',
		  publisher: 'Scribner',
		},
		{
		  id: '10',
		  title: 'To Kill a Mockingbird1',
		  author: 'Harper Lee1',
		  genre: 'Fiction',
		  publishedYear: 1960,
		  status: 'Issued',
		  description: 'A gripping tale of racial injustice and childhood innocence.',
		  isbn: '978-0-06-112008-4',
		  pages: 324,
		  language: 'English',
		  publisher: 'J.B. Lippincott & Co.',
		},
		{
		  id: '11',
		  title: '1984',
		  author: 'George Orwell1',
		  genre: 'Dystopian',
		  publishedYear: 1949,
		  status: 'Available',
		  description: 'A dystopian social science fiction novel.',
		  isbn: '978-0-452-28423-4',
		  pages: 328,
		  language: 'English',
		  publisher: 'Secker & Warburg',
		},
		{
		  id: '12',
		  title: 'Pride and Prejudice1',
		  author: 'Jane Austen1',
		  genre: 'Romance',
		  publishedYear: 1813,
		  status: 'Available',
		  description: 'A romantic novel of manners.',
		  isbn: '978-0-14-143951-8',
		  pages: 432,
		  language: 'English',
		  publisher: 'T. Egerton',
		},
		{
		  id: '13',
		  title: 'The Catcher in the Rye3',
		  author: 'J.D. Salinger3',
		  genre: 'Fiction',
		  publishedYear: 1951,
		  status: 'Issued',
		  description: 'A controversial novel about teenage rebellion.',
		  isbn: '978-0-316-76948-0',
		  pages: 277,
		  language: 'English',
		  publisher: 'Little, Brown and Company',
		},
		{
		  id: '14',
		  title: '1984',
		  author: 'George Orwell3',
		  genre: 'Dystopian',
		  publishedYear: 1949,
		  status: 'Available',
		  description: 'A dystopian social science fiction novel.',
		  isbn: '978-0-452-28423-4',
		  pages: 328,
		  language: 'English',
		  publisher: 'Secker & Warburg',
		},
		{
		  id: '15',
		  title: 'Pride and Prejudice4',
		  author: 'Jane Austen4',
		  genre: 'Romance',
		  publishedYear: 1813,
		  status: 'Available',
		  description: 'A romantic novel of manners.',
		  isbn: '978-0-14-143951-8',
		  pages: 432,
		  language: 'English',
		  publisher: 'T. Egerton',
		},
		{
		  id: '16',
		  title: 'The Catch in the Ryer5',
		  author: 'J.D.T. Salinger5',
		  genre: 'Fiction',
		  publishedYear: 1955,
		  status: 'Issued',
		  description: 'A controversial novel about teenage rebellion.',
		  isbn: '978-0-316-76948-0',
		  pages: 277,
		  language: 'English',
		  publisher: 'Little, Brown and Company',
		},
	  ];


export const genres = [
    'Fiction',
    'Non-Fiction',
    'Mystery',
    'Romance',
    'Science Fiction',
    'Fantasy',
    'Biography',
    'History',
    'Self-Help',
    'Business',
    'Technology',
    'Health',
    'Travel',
    'Cooking',
    'Art',
    'Poetry',
    'Drama',
    'Horror',
    'Thriller',
    'Adventure',
    'Comedy',
    'Crime',
    'Dystopian',
    'Educational',
    'Philosophy',
    'Psychology',
    'Religion',
    'Science',
    'Sports',
  ];

export const languages = [
    'English',
    'Spanish',
    'French',
    'German',
    'Italian',
    'Portuguese',
    'Russian',
    'Chinese',
    'Japanese',
    'Korean',
    'Arabic',
    'Hindi',
    'Other',
  ];